-  name: app-setup
   ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml  

-  name: nodejs setup
   ansible.builtin.import_role:
    name: common
    tasks_from: java.yaml

- name: installing dependencies
  ansible.builtin.pip:
     requirements: requirements.txt
     executable: pip3.9
  args:
    chdir: /app

-  name: setup systemd service
   ansible.builtin.import_role:
    name: common
    tasks_from: systemd.yaml