-  name: app-setup
    #ansible.builtin.include_role:
   ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml 
   #  tags:
   #   - deployment   # you need to set-up again in common tasks to run this 

-  name: nodejs setup
   ansible.builtin.import_role:
    name: common
    tasks_from: nodejs.yaml
   #  tags:
   #   - deployment

-  name: creating mongo repo
   ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

-  name: installing client mongodb-mongosh
   ansible.builtin.package: 
        name: mongodb-mongosh
        state: present

-  name: connect to mongodb catalogue 
   ansible.builtin.command: mongosh {{ MONGODB_HOST }} --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
   register: catalogue_output

-  name: loading data 
   ansible.builtin.shell: mongosh --host  {{ MONGODB_HOST }} </app/db/master-data.js
   when: catalogue_output.stdout | int < 0 

-  name: setup systemd service
   ansible.builtin.import_role:
    name: common
    tasks_from: systemd.yaml


   