- name: Install a Python package
  ansible.builtin.dnf:
       name:  "{{ item }}"
       state: present
  loop: 
     - python3-devel
     - python3
     -  gcc

- name: installing dependencies
  ansible.builtin.pip:
     requirements: requirements.txt
     executable: pip3.9
  args:
    chdir: /app
